//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Searches = new HashSet<Search>();
        }
    
        public int Booking_ID { get; set; }
        public Nullable<System.DateTime> Check_In_Date { get; set; }
        public Nullable<System.DateTime> Check_Out_Date { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<int> Guest_ID { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Search> Searches { get; set; }
    }
}
