//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int T_Person { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Guest_ID { get; set; }
        public Nullable<int> Rooms_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
